apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kani-system

resources:
  - namespace.yaml
  - validator-rbac.yaml
  - validator-configmap.yaml
  - validators.yaml

images:
  - name: kani-validator-image
    newName: northamerica-northeast1-docker.pkg.dev/PROJECT_ID/kani/kani-api
    newTag: latest
