apiVersion: v1
kind: Namespace
metadata:
  name: kani-system
  labels:
    app.kubernetes.io/name: kani
    app.kubernetes.io/part-of: kani-network
    kani.phase: "phase-5b"
    kani.environment: sandbox
