[package]
name = "kani-node"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
kani-consensus = { path = "../kani-consensus" }
kani-crypto = { path = "../kani-crypto" }
kani-ledger = { path = "../kani-ledger" }
kani-types = { path = "../kani-types" }
serde.workspace = true
thiserror.workspace = true
